# Generated by Django 5.0.2 on 2024-02-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('imgPath', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=30)),
                ('userRating', models.CharField(max_length=10)),
            ],
        ),
    ]
