# Generated by Django 5.0.2 on 2024-02-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalistings', '0003_alter_movie_mpaarating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='mpaaRating',
        ),
        migrations.DeleteModel(
            name='MpaaRating',
        ),
    ]
