# Generated by Django 5.0.2 on 2024-02-17 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalistings', '0012_rename_genre_genre_name_alter_genre_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre',
        ),
    ]
