# Generated by Django 5.0.2 on 2024-02-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalistings', '0016_mpaarating_remove_movie_genre_alter_genre_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpaaRating',
        ),
        migrations.AddField(
            model_name='movie',
            name='mpaaRating',
            field=models.JSONField(default={}),
        ),
    ]
